# MAIN base
baseURL = "https://www.feedflow.dev/"
defaultContentLanguage = "en"
title = "FeedFlow | RSS Reader"
description = "FeedFlow - RSS Reader for Android, iOS and MacOS"
theme = "apsho"

# Multilingual configuration
[languages]
  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    weight = 1
    title = "FeedFlow | RSS Reader"
    [languages.en.params]
      description = "FeedFlow - RSS Reader for Android, iOS and MacOS"

  # Additional languages can be added here following Weblate translations
  # Example:
  # [languages.it]
  #   languageCode = "it"
  #   languageName = "Italiano"
  #   weight = 2
  #   title = "FeedFlow | Lettore RSS"

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "FAQ"
    url = "/faq/"
    weight = 2
[[menu.sitemap]]
    name = "Show on Github"
    url = "https://github.com/prof18/feed-flow"
    weight = 3
[[menu.sitemap]]
    name = "Privacy Policy"
    url = "https://www.prof18.com/feed-flow/pp/privacy-policy-jul23/"
    weight = 4
[[menu.sitemap]]
    name = "Report issue"
    url = "https://github.com/prof18/feed-flow/issues/new?title=App+issue&body=Please+describe+the+issue+and+provide+a+link+to+the+RSS+Feed+that+causes+the+issues:%0A"
    weight = 5
[[menu.sitemap]]
    name = "Contribute with translations"
    url = "https://hosted.weblate.org/projects/feedflow/"
    weight = 6
[[menu.sitemap]]
    name = "Donations üôè"
    url = "https://www.paypal.me/MarcoGomiero"
    weight = 7

[params]

# Header
logo = "images/logo.png"

# Footer
copyright1 = "All right reserved"
copyright2 = "Copyright ¬©  <a href=\"https://www.marcogomiero.com/\" target=\"_blank\">Marco Gomiero </a> {year}"
